### ISSUE TITLE
ModuleNotFoundError: No module named 'pipe.models.oldt5'

### ISSUE THREAD

**Issue by Sunjnn** [saareliad/FTPipe#8]
When I run the command
```bash
python -m pipe.main --help
```
That error appeared, and here is the whole error information.
```bash
Traceback (most recent call last):
  File "/home/sun/.conda/envs/nompi/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sun/.conda/envs/nompi/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sun/data/FTPipe/pipe/main.py", line 16, in <module>
    from pipe.data import add_dataset_argument
  File "/home/sun/data/FTPipe/pipe/data/__init__.py", line 6, in <module>
    from .from_args_and_kw import *
  File "/home/sun/data/FTPipe/pipe/data/from_args_and_kw.py", line 7, in <module>
    from pipe.models.simple_partitioning_config import PipelineConfig
  File "/home/sun/data/FTPipe/pipe/models/__init__.py", line 1, in <module>
    from . import transformers_utils
  File "/home/sun/data/FTPipe/pipe/models/transformers_utils.py", line 3, in <module>
    from .transformers_cfg import MODEL_TYPES
  File "/home/sun/data/FTPipe/pipe/models/transformers_cfg.py", line 883, in <module>
    from pipe.models.oldt5 import oldt5_functions_list
ModuleNotFoundError: No module named 'pipe.models.oldt5'
```
It seems lacking a source file in the dir `pipe/models/`.

**Comment by saareliad** [comment]
Thanks, @Sunjnn , yes it is a reminder from experiments with an old model version that wasn't pushed to git.
The last commit shall fix it.

**Comment by Sunjnn** [comment]
Thanks for your answer.
